### ISSUE TITLE
Suffix or Prefix bits to find corresponding bucket?

### ISSUE THREAD

**Issue by yuanjingsong** [fallfish/AustereCache#1]
Hi Qiuping! I find that using suffix bits of LBA-hash to identify bucket in your paper, but when i look the code (src/metadata/index.cc), it seems like you used left shift operation, which means using prefix bits to identify bucket. So, I'm confused about that. Can u explain it?

**Comment by fallfish** [comment]
Hi Yuanjing. Thanks for your question! Sorry that I didn’t notice your question earlier.

As you pointed out, in the implementation I actually used prefix bits for the bucket identification and suffix bits as the lookup key in each slot, which is not fully consistent with the description in the paper. However, this should not affect the results since we always use part of the hash value for the bucket identification and the remaining part for indexing the slots. Sorry for the confusion caused.

You can also drop me email any time if you found me not so responsive at github or you have any further questions.
Again, thanks for pointing out the inconsistency.
