### ISSUE TITLE
How much capacity do I need

### ISSUE THREAD

**Issue by RershallzzZ** [fallfish/AustereCache#2]
hi！
How much capacity do I need to run your code?
I gave 35GB and still ran out of space

**Comment by fallfish** [comment]
Hi, thanks for your question. Sorry for the late reply.

Can you elaborate on how you run the program so that I can figure out what is the problem? The space required should depend on your configuration.

I assume you are referring to replaying the FIU traces. The capacity required should be of the largest LBA of the I/O requests in the trace, in which case you may need a device whose capacity exceeds the largest LBA. For example, we use a separate HDD with 1TB capacity as the primary storage and issue direct I/Os to the raw device with root privilege to evaluate the performance.

Or if you are using a local file, the capacity of the remaining storage space should be larger than the working set size of the specified trace since the file system should well manage a sparse file.
