### ISSUE TITLE
The "Not match" problem.

### ISSUE THREAD

**Issue by LongTengYiFei** [fallfish/AustereCache#6]
I want to execute the Exp#8 in the Home trace.
I use chunk size 32KiB, subchunk size 8KiB, WriteBackpolicy, i meet "Not match" in the dirtylist_austerecache.cc.
wss:32GB    cache size:4GB    primary size:32GB

**The output:**
Not match!
11
96142393344
24576 16384

**The partial json:**
```
  "primaryDeviceSize": 34359738368,
  "cacheDeviceSize": 4294967296,
  "workingSetSize": 34359738368,

  "chunkSize": 32768,
  "subchunkSize": 8192,
  "nSlotsPerLbaBucket": 128,
  "nSlotsPerFpBucket": 128,
  "nBitsPerLbaSignature": 16,
  "nBitsPerFpSignature": 16,
  "lbaAmplifier": 4,

  "syntheticCompression": 1,
  "compactCachePolicy": 1,
  "sketchBasedReferenceCounter": 1,

  "multiThreading": 0,
  "nThreads": 1,
  "cacheMode": "WriteBack",
  "weuSize": 2097152,

  "directIO": 1,
  "traceReplay": 1,
  "fakeIO": 1,
```
But when i just change the WriteBack to WriteThrough, it works well.

**Comment by LongTengYiFei** [comment]
By the way，when i use trace, i delete the first line of it (homes_final_trace_00.txt).

**Comment by LongTengYiFei** [comment]
I find that, maybe it is due to the code in the 
void MetadataModule::update(Chunk &chunk)
src/metadata/metadata_module.cc
```
#ifdef ACDC
    if (Config::getInstance().getCacheMode() == tWriteBack) {
      DirtyList::getInstance().addLatestUpdate(chunk.addr_,
          chunk.cachedataLocation_,
          (chunk.nSubchunks_ + 1) *
          Config::getInstance().getSubchunkSize());
    }
#endif
```
i make breakpoint in the program, the compressed length of this chunk is 16041, the nSubchunks is 2, the nSubchunks+1 then multiply subChunkSize will cause the len is 24KiB, i guess the error message 24KiB not equal 16KiB is it.

**Comment by LongTengYiFei** [comment]
i want to ask, why the nSubchunks must plus 1?

**Comment by fallfish** [comment]
Hi LongTengYiFei,

Apologies for the issue, and thanks for pointing out the case. It turns out that the chunk.nSubchunks + 1 is indeed a bug in the open source repo :(, and the bug triggers 100% at each run with AustereCache write-back policy.

I examined my private repo which tracks the development. The corresponding line was "(chunk.compressedLevel_ + 1)" which started from 0 rather than 1 as in nSubchunks. When I open source the code, I tidied up some of the namings, but did not re-examine whether all the experiments could run as expected.

Yours Sincerely,
Qiuping
